on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - dev

name: "Build & Release"
jobs:
  build:
    name: Build & Release
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Build Android APK
        run: flutter build apk --release --split-per-abi

      - name: Build iOS
        run: flutter build ios --release --no-codesign --no-tree-shake-icons

      - name: Push Android artifacts to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}

      - name: Push iOS artifacts to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/ios/Release/*.ipa"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
